<?php

use Drupal\Core\Routing\RouteMatchInterface;
//use Drupal\Core\Database\Database;

/**
 * Implements hook_help().
 */
function foxywp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.foxywp':
      $output = '';
      $output .= '<h3>' . t('My first hook') . '</h3>';
      $output .= '<p>' . t('This is module about cats.') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_theme().
 */
function foxywp_theme($existing, $type, $theme, $path) {
  return [
    'name-twig'=>[
      'render element'=>'form',
      'varibles'=>[
        'form' => NULL,
      ]
    ],
  ];
}







