<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;

/**
 * Implements hook_help().
 */
function foxywp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.foxywp':
      $output = '<h3>' . t('My first hook') . '</h3>';
      $output .= '<p>' . t('This is module about cats exhibition.') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return array
 */
function foxywp_theme($existing, $type, $theme, $path): array {
  return [
    'cat_twig' => [
      //      'render element'=>'form',
      'variables' => [
        'form' => [],
        'table' => [],
        'image' => NULL,
        'results' => NULL
      ],
    ],
  ];
}











