<?php

/**
 * @file
 * Primary module hooks for Temp module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */


use Drupal\Core\Routing\RouteMatchInterface;
//use Drupal\Core\Database\Database;

/**
 * Implements hook_help().
 */
function temp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.temp':
      $output = '';
      $output .= '<h3>' . t('My first hook') . '</h3>';
      $output .= '<p>' . t('This is module about cats.') . '</p>';
      return $output;
    default:
  }
}

